SR155Organiztion/SR_Overcooked2

Client/Code/CRealPlayer.cpp
Client/Header/CRealPlayer.h
Client/Include/Client.vcxproj
Client/Include/Client.vcxproj.filters
Engine/Header/CAniMat.h
Engine/Header/CCollision.h
Engine/Header/CPhysics.h
Engine/Include/Engine.vcxproj
Engine/Include/Engine.vcxproj.filters
Reference/Header/CAniMat.h
Reference/Header/CCollision.h
Reference/Header/CPhysics.h

[Feat] : 플레이어 설계안 작성

---

Client/Code/CRealPlayer.cpp
Client/Header/CRealPlayer.h

[Docs] : 플레이어 문서

---

Client/Code/CLoading.cpp
Client/Code/CRealPlayer.cpp
Client/Code/CStage.cpp
Client/Header/CRealPlayer.h

[Feat] : Player Render

---

Client/Code/CFakePlayer.cpp
Client/Code/CLettuceTemp.cpp
Engine/Code/CPhysicsMgr.cpp
Engine/Header/CPhysicsMgr.h
Engine/Header/CTransform.h
Engine/Header/Engine_Macro.h
Engine/Header/IPhysics.h
Reference/Header/CPhysicsMgr.h
Reference/Header/CTransform.h
Reference/Header/Engine_Macro.h
Reference/Header/IPhysics.h

[Feat] : 중력 적용

---

Client/Code/CDynamicCamera.cpp
Client/Code/CLoading.cpp
Client/Header/CDynamicCamera.h

[Feat]: Camera move

---

Client/Code/CUiMgr.cpp
Client/Code/CUi_Button.cpp
Client/Header/CUi_Button.h
Engine/Code/CDInputMgr.cpp

[Feat] UI 버튼 이동 속도 조정

---

Client/Code/CPasta.cpp
Client/Code/CPot.cpp
Client/Code/CRealPlayer.cpp
Client/Code/CStage.cpp
Client/Header/CPot.h
Client/Header/CRealPlayer.h
Client/Include/Client.vcxproj.filters

- 물리 충돌 테스트 위해 플레이어, 파스타, 냄비에 물리 적용해서 올립니다.

[test] : 오브젝트 물리 충돌 테스트

---

Engine/Code/CPhysicsMgr.cpp
Engine/Header/IPhysics.h
Reference/Header/IPhysics.h

[Fix] : 물리옵션중 충돌 옵션 추가

---

Engine/Code/CPhysicsMgr.cpp
Engine/Header/IPhysics.h
Reference/Header/IPhysics.h

[Feat] : 충돌시 On_Collision함수 호출

---

Client/Code/CStage.cpp
Client/Header/CStage.h

[Feat] : JSON 파싱

---

Engine/Code/CPhysicsMgr.cpp
Engine/Header/IPhysics.h
Reference/Header/IPhysics.h

[Feat] : Detect 함수 생성

---

Engine/Code/CPhysicsMgr.cpp

[Feat] : 넉백 없는 오브젝트도 탐지

---

Client/Code/CLoading.cpp
Client/Code/CMenu.cpp
Client/Code/CStage.cpp
Client/Code/CStageLoading.cpp
Client/Header/CLoading.h

[Fix] UI 호출 위치 수정

---

Client/Code/CHandState.cpp
Client/Code/CPlayerHand.cpp
Client/Code/CPlayerState.cpp
Client/Code/CRealPlayer.cpp
Client/Header/CHandState.h
Client/Header/CPlayerHand.h
Client/Header/CRealPlayer.h

[Feat] : Player Wash 애니메이션 추가

---

Client/Code/CHandState.cpp
Client/Code/CPlayerHand.cpp

[Feat] : Player Wash 애니메이션 추가 #4

---

Client/Code/CCucumber.cpp
Client/Code/CFish.cpp
Client/Code/CFryingpan.cpp
Client/Code/CLettuce.cpp
Client/Code/CLoading.cpp
Client/Code/CPasta.cpp
Client/Code/CPlate.cpp
Client/Code/CPot.cpp
Client/Code/CRice.cpp
Client/Code/CSeaweed.cpp
Client/Code/CShrimp.cpp
Client/Code/CStage.cpp
Client/Code/CTomato.cpp
Client/Header/CPlate.h
Client/Header/IProcess.h

- 냄비, 후라이팬에서 조리하는 밥, 파스타, 토마토 소스(아직 구현 안함)이 접시에 올라가도록 구현
- (토마토 소스 제외한) 모든 재료 조합대로 올라가는지 테스트 완료
- 이미지 소스가 없는 조합대로 올릴 경우 접시를 초기화하도록 처리

[Feat] : Plate에 냄비, 후라이팬 위에 있는 음식 올리기 구현

---

Engine/Code/CMapTool.cpp
Engine/Header/CMapTool.h
Reference/Header/CMapTool.h

- json에서 데이터를 가져오는 구조를 변경하였습니다.

[Fix] : json 데이터 불러오기 해결 (#26)

---

Client/Code/CHandState.cpp
Client/Code/CPlayerHand.cpp
Client/Code/CRealPlayer.cpp
Client/Code/CStage.cpp
Client/Header/CHandState.h
Client/Header/CRealPlayer.h
Client/Header/Player_Define.h

[Fix] : Player와 환경오브젝트 (Station, 식기류, 재료) 상호작용 업데이트

---

Client/Code/CFryingpan.cpp
Client/Code/CGasStation.cpp
Client/Code/CPlate.cpp
Client/Code/CPot.cpp
Client/Code/CRice.cpp
Client/Header/CFryingpan.h
Client/Header/CPot.h

- 냄비랑 후라이팬에 재료를 담고 가스레인비가 아닌 다른 스테이션에 올렸을 때 조리되는 버그 해결

[Fix] : 가스레인지 아닌 곳에 냄비, 후라이팬 올라갔을 때 조리되는 버그 해결

---

Client/Code/CUi_Order.cpp
Client/Header/CUi_Order.h

[Feat] Order 호출 시 애니메이션 효과 추가

---

Client/Code/CHandState.cpp
Client/Code/CPlayerHand.cpp
Client/Code/CRealPlayer.cpp
Client/Header/CHandState.h
Client/Header/CPlayerHand.h
Client/Header/CRealPlayer.h
Client/Header/Player_Define.h
Client/Include/Client.vcxproj

[Feat] : Player Animation - Throw 추가

---

Client/Code/CDummyEffect.cpp
Client/Code/CLoading.cpp
Client/Code/CRealPlayer.cpp
Client/Code/CStage.cpp
Client/Header/CDummyEffect.h
Client/Header/CRealPlayer.h
Client/Header/Player_Define.h
Client/Include/Client.vcxproj
Client/Include/Client.vcxproj.filters

[Docs] : Player Docs Update

---

Client/Code/CStage.cpp
Client/Code/CStageLoading.cpp
Client/Code/CUi_Order.cpp
Client/Header/CUi_Factory.h
Client/Header/CUi_Order.h

[Feat] Order UI 종류 추가

---

Client/Header/CPlate.h

- CPlate에 멤버변수로 있는 set<wstring> m_setIngredient를 반환하는 Get_Ingredient() 함수 추가

[Feat] : Plate에 Get_Ingredient 추가

---

Client/Code/CMenu.cpp
Client/Code/CSelect.cpp
Client/Code/CStage.cpp
Client/Code/CStageLoading.cpp
Client/Code/CUi_Order.cpp
Client/Code/CUi_Score.cpp
Client/Code/CUi_Timer.cpp
Client/Header/CUi_Order.h
Client/Header/CUi_Score.h
Client/Header/CUi_Timer.h
Client/Include/Client.vcxproj
Client/Include/Client.vcxproj.filters

1번째 Order UI가 사라질 경우, 남은 UI가 비어있는 크기만큼 왼쪽으로 이동정렬

[Feat] Order UI 이동정렬

---

Client/Code/CUi_Order.cpp
Client/Code/CUi_Score.cpp
Client/Code/CUi_Timer.cpp
Client/Header/CUi_Order.h
Client/Header/CUi_Score.h
Client/Header/CUi_Timer.h

-UI Score 함수 추가 (Set)
-Ui Timer Get 함수의 매개변수 변경

[Fix] UI 함수명 변경 및 추가

---

Engine/Code/CLayer.cpp
Engine/Header/CGameObject.h
Reference/Header/CGameObject.h

[Feat] : 게임 오브젝트 id값 부여

---

Client/Code/CUi_Order.cpp
Client/Header/CUi_Order.h

[Fix] Order UI enum 수정

---

Client/Code/CUi_Order.cpp
Client/Header/CUi_Order.h
Reference/Header/CObjectPoolMgr.h

- Order UI 종류별 크기 및 간격 수정
- Make_Order 매개변수명 수정

[Feat] Order UI 종류별 크기 및 간격 수정

---

Client/Code/CFryingpan.cpp
Client/Code/CPlate.cpp
Client/Code/CPot.cpp
Client/Code/CRice.cpp
Client/Header/IPlace.h

- 재료를 조리해서 접시에 올리면 재료를 ObjectPool로 반환하고, 레이어 맵 컨테이너에서 오브젝트를 지움
- 냄비나 후라이팬에서 조리한 재료를 접시에 담을 경우 접시에서 냄비, 후라이팬을 Set_Empty() 호출

[Feat] : 접시에 재료 올라가면 재료를 ObjectPool로 반환

---

Client/Code/CInGameSystem.cpp
Client/Code/CStage.cpp
Client/Code/CUi_Order.cpp
Client/Code/CUi_Score.cpp
Client/Header/CInGameSystem.h
Client/Header/CUi_Order.h
Client/Header/CUi_Score.h
Engine/Code/CPhysicsMgr.cpp

[Feat] : UI 업데이트 및 파싱 업데이트

---

Client/Code/CInGameSystem.cpp

[Fix] : 시간제한 하드코딩 제거

---

Client/Code/CLoading.cpp

- Loading.cpp에 파스타 텍스쳐 중복으로 삭제

[Fix] : texture 중복 오류

---

Client/Code/CInGameSystem.cpp
Client/Header/CInGameSystem.h

[Feat] : Scene update

---

Client/Code/CChopStation.cpp
Client/Code/CFryingpan.cpp
Client/Code/CPlate.cpp
Client/Code/CTomatoSoup.cpp
Client/Code/CTrashStation.cpp
Client/Header/CFryingpan.h
Client/Header/CIngredient.h

- 토마토스프 추가해서 요리하고, 토마토 파스타 만들어서 제출 됨

[Feat] : 토마토 파스타

---

Client/Code/CInGameSystem.cpp
Client/Code/CRealPlayer.cpp
Client/Code/CStage.cpp
Client/Header/CInGameSystem.h
Client/Header/CRealPlayer.h

[Feat] : Map tool 플레이어 초기 설정

---

Client/Code/CEffect.cpp
Client/Code/CUi_Button.cpp
Client/Code/CUi_CookLoding.cpp
Client/Code/CUi_Gauge.cpp
Client/Code/CUi_Icon.cpp
Client/Code/CUi_Order.cpp
Client/Code/CUi_Score.cpp
Client/Code/CUi_TimeLimit.cpp
Client/Header/CUi.h
Client/Header/CUi_Button.h
Client/Header/CUi_CookLoding.h
Client/Header/CUi_Gauge.h
Client/Header/CUi_Icon.h
Client/Header/CUi_Order.h
Client/Header/CUi_TimeLimit.h

- CUI 구조체 추가
- 그외 UI 클래스에서 변수 수정

[Feat] UI 구조체 추가 및 수정

---

Client/Code/CLoading.cpp
Client/Code/CStage.cpp
Client/Code/CUi_CookLoding.cpp
Client/Code/CUi_Icon.cpp
Client/Code/CUi_Order.cpp
Client/Header/CUi.h
Client/Header/CUi_CookLoding.h
Client/Header/CUi_Factory.h
Client/Header/CUi_Icon.h
Client/Include/Client.vcxproj
Client/Include/Client.vcxproj.filters
Engine/Code/CSprite.cpp

[Feat] ICON 추가 생성 중

---

Client/Code/CCleanPlateStation.cpp
Client/Code/CDirtyPlateStation.cpp
Client/Code/CInvisibleStation.cpp
Client/Code/CLoading.cpp
Client/Code/CSinkStation.cpp
Client/Code/CStage.cpp
Client/Header/CInvisibleStation.h

- InvisibleStation 회색 박스 큐브로 클래스 만들어 놓음
- 설거지를 완료해서 접시가 깨끗해지면 CleanPlateStation 위에 올려놓게 처리
- DirtyPlateStation 위에 더러운 접시만 올라가도록 추가

[Feat] : InvisibleStation, CleanPlateStation

---

Client/Code/CUi_Icon.cpp
Client/Header/CUi_Factory.cpp
Client/Header/CUi_Factory.h
Client/Header/CUi_Icon.h

[Fix] 오류 수정

---

Client/Code/CUi_Icon.cpp
Client/Header/CUi.h
Client/Header/CUi_Factory.h
Client/Header/CUi_Icon.h

[Feat] 아이콘 UI 호출

---

Client/Code/CUi_Icon.cpp
Client/Header/CUi_Icon.h

[Fix] Icon 리턴값 추가

---

Client/Code/CEmptyStation.cpp
Client/Code/CStage.cpp
Client/Header/CEmptyStation.h
Engine/Code/CPhysicsMgr.cpp
Engine/Header/CPhysicsMgr.h
Reference/Header/CPhysicsMgr.h

Snap 함수 처리

---

Client/Code/CInGameSystem.cpp
Client/Header/CUtil.h

[Feat] : 랜덤 함수 타입 검사 추가

---

Base/CBase.inl
Client/Code/CRealPlayer.cpp
Client/Code/CStage.cpp
Client/Header/CRealPlayer.h

[Feat] : SinkStation과 Player 상호작용 연결

---

Client/Code/CIngredient.cpp
Client/Code/CIngredientStation.cpp
Client/Code/CLoading.cpp
Client/Code/CStage.cpp
Client/Header/CIngredient.h
Client/Header/CIngredientStation.h
Engine/Code/CCamera.cpp
Engine/Code/CGameObject.cpp
Engine/Code/CObjectPoolMgr.cpp
Engine/Header/CGameObject.h
Engine/Header/CObjectPoolMgr.h
Reference/Header/CGameObject.h
Reference/Header/CObjectPoolMgr.h

재료상자는 z축으로 -3즈음 만들어놨어요
카메라 바깥에있습니다

[Feat] : 재료 상자 구현 및 오브젝트풀매니저 연동

---

Engine/Code/CPhysicsMgr.cpp

[Fix] : 스냅시 멈춤 적용 #223

---

Engine/Code/CPhysicsMgr.cpp

[Feat] : 물리 y축 충돌 보정 적용

---

Client/Code/CChopStation.cpp
Client/Code/CIngredientStation.cpp
Client/Code/CRealPlayer.cpp
Client/Code/CTrashStation.cpp
Client/Header/CChopStation.h
Client/Header/CIngredientStation.h
Client/Header/CTrashStation.h
Engine/Code/CPhysicsMgr.cpp

empty, ingredient, chop, trash station에 적용

[Feat] : Snap가능한 Station에 On_Snap적용 #226

---

Client/Code/CPlayerHand.cpp
Client/Code/CRealPlayer.cpp
Client/Code/CStage.cpp
Client/Code/CTestEffect.cpp
Client/Header/CRealPlayer.h

Player와 Tool상호작용 수정 및 커서 하이라이트 적용

[Fix] : Player와 Tool상호작용 수정 및 커서 하이라이트 적용 및 이펙트 빌보드적용

---

Client/Code/CFryingpan.cpp
Client/Code/CIngredient.cpp
Client/Code/CPlate.cpp
Client/Code/CPot.cpp
Client/Code/CServingStation.cpp
Client/Code/CStage.cpp
Client/Code/CTrashStation.cpp
Client/Code/IState.cpp
Client/Header/CIngredient.h
Engine/Code/CGameObject.cpp
Engine/Code/CLayer.cpp
Engine/Code/CObjectPoolMgr.cpp
Engine/Header/CGameObject.h
Reference/Header/CGameObject.h

- 재료를 접시, 쓰레기통에 버리거나 접시를 서빙스테이션에 넣을 때 오브젝트 풀로 반환하도록 수정
- 오브젝트풀로 반환될 때 재료 상태 리셋되도록 추가

[Fix] : 오브젝트풀로 반환하는 부분 수정

---

Engine/Code/CPhysicsMgr.cpp

[Fix] : 구르기 제거

---

Client/Code/CChopStation.cpp
Client/Code/CEmptyStation.cpp
Client/Code/CGasStation.cpp
Client/Code/CIngredientStation.cpp
Client/Code/CTrashStation.cpp
Client/Header/CGasStation.h

스테이션 위에 있는 도구에 재료가 스냅되지 않는(들어가지 않는) 버그 수정했습니다

[Fix] : 스테이션 위 도구에 재료 스냅 수정

---

Client/Code/CInGameSystem.cpp
Client/Header/CUtil.h

[Feat] : 재료상자 파싱추가

---

Client/Code/CChopStation.cpp
Client/Code/CIngredient.cpp
Client/Code/CRealPlayer.cpp
Client/Code/CUi_Icon.cpp
Client/Code/CUi_WarningBox.cpp
Client/Header/CChopStation.h
Client/Header/CRealPlayer.h
Client/Header/CUi_Icon.h

[Fix] 아이콘 종류별 호출 에러 수정

---

Client/Code/CCucumber.cpp
Client/Code/CFish.cpp
Client/Code/CFryingpan.cpp
Client/Code/CInteract.cpp
Client/Code/CLettuce.cpp
Client/Code/CPasta.cpp
Client/Code/CPlate.cpp
Client/Code/CPot.cpp
Client/Code/CRice.cpp
Client/Code/CSeaweed.cpp
Client/Code/CShrimp.cpp
Client/Code/CTomato.cpp
Client/Code/CTomatoSoup.cpp
Client/Header/CInteract.h

[Feat] : 재료, 도구에 빌보드 적용

---

Client/Code/CInGameSystem.cpp
Client/Code/CUi_Icon.cpp
Client/Code/CUi_Order.cpp
Client/Header/CUi.h
Client/Header/CUi_CookLodingBox.h
Client/Header/CUi_Icon.h

Order UI에서 종류 별로 출력 되지 않는 오류 수정

[Fix] Order UI 출력 오류 수정

---

Client/Code/CChopStation.cpp
Client/Code/CFryingpan.cpp
Client/Code/CPlate.cpp
Client/Code/CPot.cpp
Client/Header/CChopStation.h
Client/Header/CFryingpan.h
Client/Header/CPlate.h
Client/Header/CPot.h

- 재료에 아이콘 추가
- 찹스테이션, 냄비, 후라이팬에 프로그레스바 추가
- 냄비, 후라이팬에 경고창 추가
- 아이콘을 보이게/안 보이게 하는 처리는 추후 함수가 만들어지면 할 예정

[Feat] : 오브젝트에 아이콘 추가

---

Client/Code/CChopStation.cpp
Client/Code/CInGameSystem.cpp
Client/Code/CRealPlayer.cpp
Client/Code/CUi_Icon.cpp
Client/Code/CUi_Order.cpp
Client/Code/CUi_WarningBox.cpp
Client/Header/CChopStation.h
Client/Header/CUi.h
Client/Header/CUi_CookLodingBox.h
Client/Header/CUi_Icon.h
Client/Header/CUi_WarningBox.h

[Fix] 보이기/ 감추기 함수 추가

---

Client/Code/CRealPlayer.cpp
Client/Code/CUi_WarningBox.cpp

[Fix] 병합 오류 수정

---

Client/Code/CRealPlayer.cpp
Client/Code/CUi_Button.cpp
Client/Code/CUi_CookLoding.cpp
Client/Code/CUi_CookLodingBox.cpp
Client/Code/CUi_Gauge.cpp
Client/Code/CUi_Icon.cpp
Client/Code/CUi_Order.cpp
Client/Code/CUi_Score.cpp
Client/Code/CUi_Timer.cpp
Client/Code/CUi_WarningBox.cpp
Client/Header/CUi.h
Client/Header/CUi_CookLoding.h
Client/Header/CUi_CookLodingBox.h
Client/Header/CUi_Gauge.h
Client/Header/CUi_Icon.h
Client/Header/CUi_Order.h
Client/Header/CUi_WarningBox.h

[Fix] Icon 에러 해결

---

Client/Code/CChopStation.cpp
Client/Code/CCleanPlateStation.cpp
Client/Code/CDirtyPlateStation.cpp
Client/Code/CEmptyStation.cpp
Client/Code/CFryingpan.cpp
Client/Code/CGasStation.cpp
Client/Code/CIngredient.cpp
Client/Code/CIngredientStation.cpp
Client/Code/CPlate.cpp
Client/Code/CPot.cpp
Client/Code/CServingStation.cpp
Client/Code/CSinkStation.cpp
Client/Code/CTrashStation.cpp
Client/Code/IState.cpp
Client/Header/CChopStation.h
Client/Header/CFryingpan.h
Client/Header/CIngredient.h
Client/Header/CPlate.h
Client/Header/CPot.h
Engine/Code/CObjectPoolMgr.cpp
Engine/Header/CGameObject.h
Reference/Header/CGameObject.h

- 재료 위 아이콘 추가 (재료에 따라 조리 이후에 아이콘이 뜨기도)
- 조리도구에서 재료를 손질 할 때 진행도가 뜨고, 경고창이 깜빡 거리게 추가
- 접시에 재료를 추가하면 해당하는 재료 아이콘 뜨도록 추가

[Feat] : 재료 아이콘 / 조리도구 진행도, 경고창 / 접시 아이콘 추가

---

Client/Code/CLoading.cpp
Client/Code/CStage.cpp
Client/Code/CUi_Timer.cpp
Client/Header/CUi_Timer.h
Client/Include/CUi_TimeOut.cpp
Client/Include/CUi_TimeOut.h
Client/Include/Client.vcxproj
Client/Include/Client.vcxproj.filters

[Feat] 준비 시작, 타임아웃 등 UI 추가

---

Client/Code/CDirtyPlateStation.cpp
Client/Code/CServingStation.cpp
Client/Header/CDirtyPlateStation.h

- 서빙 이후에 돌아오는 접시를 쌓게 구현
- 제일 먼저 들어온 접시는 위에, 마지막에 들어온 접시는 아래에 쌓임
- 쌓인 접시에 재료를 놓으면 맨 위에 접시에 올라감

[Feat] : 서빙 후 돌아오는 접시 쌓기

---

Client/Code/CPlayerState.cpp
Client/Code/CRealPlayer.cpp
Client/Code/CStage.cpp
Client/Header/CPlayerState.h
Client/Header/CRealPlayer.h

1p 이동 T:위, F:왼쪽 G:아래, H:오른쪽 
Z:상호작용 X:잡기 C: 대쉬
2p 이동 방향키
, :상호작용  . :잡기  / : 대쉬

[Feat] : Player 2P 구현

---

Base/CBase.inl
Client/Code/CBus.cpp
Client/Code/CLoading.cpp
Client/Code/CSelect.cpp

[Feat] : 스테이지 선택 창 버스(플레이어)구현

---

Client/Code/CHandState.cpp
Client/Code/CPlayerHand.cpp
Client/Code/CRealPlayer.cpp
Client/Header/CHandState.h
Client/Header/CPlayerHand.h
Client/Header/Player_Define.h

[Feat] : Player Surprise 추가

---

Client/Code/CLoading.cpp
Client/Code/CWoodTile.cpp
Client/Header/CWoodTile.h
Client/Include/Client.vcxproj
Client/Include/Client.vcxproj.filters

[Feat] WoodTile 추가

---

Client/Code/CAnyEffect.cpp
Client/Code/CCloudEffect.cpp
Client/Code/CHandState.cpp
Client/Code/CHitEffect.cpp
Client/Code/CLoading.cpp
Client/Code/CPlayerState.cpp
Client/Code/CRealPlayer.cpp
Client/Code/CStage.cpp
Client/Header/CAnyEffect.h
Client/Header/CCloudEffect.h
Client/Header/CHandState.h
Client/Header/CHitEffect.h
Client/Header/CPlayerState.h
Client/Header/CRealPlayer.h
Client/Include/Client.vcxproj
Client/Include/Client.vcxproj.filters
Engine/Code/CEffectMgr.cpp
Engine/Header/CEffect.h
Engine/Header/CEffectMgr.h
Reference/Header/CEffect.h
Reference/Header/CEffectMgr.h

AnyEffect 추가 및 Player Dash 이펙트 보완

[Feat] : AnyEffect 추가 및 Player Dash 이펙트 보완

---

Client/Code/CHandState.cpp
Client/Code/CRealPlayer.cpp

[Fix] : Player 소화기 상호작용 수정

---

Client/Code/CBrickWall.cpp
Client/Code/CLoading.cpp
Client/Code/CPondTile.cpp
Client/Code/CRoadTile.cpp
Client/Code/CRoofTile.cpp
Client/Header/CBrickWall.h
Client/Header/CPondTile.h
Client/Header/CRoadTile.h
Client/Header/CRoofTile.h
Client/Include/Client.vcxproj
Client/Include/Client.vcxproj.filters

- 타일 3종 추가 (RoofTile, PondTile, RoadTile)
- PondTile, RoadTile은 큰 이미지 한 장으로 배경 역할 (피지컬로 스케일, 위치 맞춰놓음)
- BrickWall에 텍스쳐 1개 추가하여 Set_Texture 함수 호출해서 설정할 수 있음 (stage 2에 들어갈 텍스쳐 추가)

[Feat] : 타일 3종 추가 / BrickWall에 텍스쳐 추가

---

Client/Code/CExtinguishEffect.cpp
Client/Code/CLoading.cpp
Client/Code/CRealPlayer.cpp
Client/Code/CStage.cpp
Client/Header/CExtinguishEffect.h
Client/Header/CRealPlayer.h
Client/Include/Client.vcxproj
Client/Include/Client.vcxproj.filters

소화기용 이펙트 구현. 
이펙트 스프라이트는 교체 필요 요망.
임시적으로 플레이어 look방향으로 2.5칸정도 발사됨
테스트 = DIK_2

[Feat] : 소화기용 이펙트 구현 #21

---

Client/Code/CCleanPlateStation.cpp
Client/Code/CDirtyPlateStation.cpp
Client/Code/CInvisibleStation.cpp
Client/Code/CServingStation.cpp
Client/Code/CSinkStation.cpp
Client/Header/CCleanPlateStation.h
Client/Header/CDirtyPlateStation.h
Client/Header/CInvisibleStation.h
Client/Header/CSinkStation.h

- DirtyPlate : 해당 스테이지에 싱크대가 있으면 더러운 접시, 없으면 깨끗한 접시 리턴
- CleanPlate : 싱크대에서 설거지하고 접시 쌓이게
- Invisible에 I 키 누르면 보이게, 안보이게

[Fix] : 접시 리턴 수정

---

Client/Code/CBamboo.cpp
Client/Code/CBarrier.cpp
Client/Code/CBasket.cpp
Client/Code/CBrickWall.cpp
Client/Code/CCar.cpp
Client/Code/CCherryTree.cpp
Client/Code/CCone.cpp
Client/Code/CHydrant.cpp
Client/Code/CPigeon.cpp
Client/Code/CSandbag.cpp
Client/Code/CTable.cpp
Client/Code/CTorch.cpp
Client/Code/CTrafficLight.cpp
Client/Code/CWoodWall.cpp

- Set_Scale 함수 내부에 if(m_pTransformCom)을 if(!m_pTransformCom) 으로 수정
- 벽 4종 (CBrickWall, CWoodWall, CBasket, CBarrier) / 데코 10종 (CCherryTree, CCar, CBamboo, CTorch, CTrafficLight, CHydrant, CCone, CPigeon, CSandbag, CTable)

[Fix] : Set_Scale 함수 오류 수정

---

Client/Code/CDirtyPlateStation.cpp
Client/Code/CSinkStation.cpp
Engine/Code/CObjectPoolMgr.cpp

[Fix] : 접시 반환 오류 해결

---

Client/Code/CUi_Timer.cpp
Client/Header/CUi_Timer.h

[Feat] 타이머 get 함수 추가

---

Client/Code/CLoading.cpp
Client/Code/CSelect.cpp
Client/Code/CUi_Score.cpp
Client/Code/CUi_Timer.cpp
Client/Header/CUi_Timer.h

[Fix] 타이머 Get함수 반환 값 수정

---

Client/Code/CUi_Score.cpp
Client/Code/CUi_StageNumber.cpp
Client/Code/CUi_Timer.cpp
Client/Header/CUi_Score.h
Client/Header/CUi_Timer.h

[FIx] 코인 에러 수정 중

---

Client/Code/CUi_StageNumber.cpp
Client/Code/CUi_Timer.cpp
Client/Header/CUi_Timer.h

[Fix] 타이머 Get함수 반환값 수정

---

Client/Code/CLoading.cpp
Client/Code/CRealPlayer.cpp
Client/Code/CStage.cpp
Client/Code/CStageLoading.cpp
Client/Code/CUi_BurntFood.cpp
Client/Code/CUi_Fadeout.cpp
Client/Code/CUi_PostCard.cpp
Client/Code/CUi_StageInfo.cpp
Client/Code/CUi_Timer.cpp
Client/Code/CUi_WarningBox.cpp
Client/Header/CRealPlayer.h
Client/Header/CUi.h
Client/Header/CUi_BurntFood.h
Client/Header/CUi_PostCard.h
Client/Include/Client.vcxproj
Client/Include/Client.vcxproj.filters

[Fix] 타이머 제한시간 설정 변경

---

Client/Code/CMenu.cpp
Client/Code/CUi_BurntFood.cpp
Client/Code/CUi_Fadeout.cpp
Client/Header/CUi_Fadeout.h

[Feat] 화재 경보 추가

---

Client/Code/CRealPlayer.cpp
Client/Code/CUi_Fadeout.cpp
Client/Header/CUi_Order.h

[Feat] 주문서 삭제 시 알림

---

Client/Code/CBamboo.cpp
Client/Code/CCone.cpp
Client/Header/CBamboo.h
Client/Header/CCone.h

- Bamboo 텍스쳐 2종으로 (왼쪽, 오른쪽)
- CCone 텍스쳐 3종으로 (왼쪽, 오른쪽, 오른쪽) 추가
- Set_Texture() 함수에 인덱스 값으로 넣어주면 됨

[Fix] : Deco 시점에 따라 텍스쳐 추가

---

Client/Code/CStage.cpp
Client/Code/CUi_BurntFood.cpp
Client/Code/CUi_Fadeout.cpp
Client/Header/CUi.h

[Fix] 화재경보 아이콘 위치 오류 수정

---

Client/Code/CLoading.cpp
Client/Code/CMenu.cpp
Client/Code/CStage.cpp
Client/Code/CStageLoading.cpp
Client/Code/CUi_Fadeout.cpp
Client/Code/CUi_GameLoding.cpp
Client/Header/CUi.h
Client/Header/CUi_GameLoding.h

[Feat] 로딩 화면 추가

---

Client/Code/CLoading.cpp
Client/Code/CRoadTile.cpp
Client/Header/CRoadTile.h

- 4스테이지 이미지 추가해서 CRoadTile에 Set_Texture로 지정할 수 있게 추가

[Feat] : 4스테이지 이미지 추가해서 CRoadTile에 Set_Texture로 지정할 수 있게 추가

---

Client/Code/CUi_CookLoding.cpp
Client/Code/CUi_CookLodingBox.cpp
Client/Code/CUi_GameLoding.cpp

[Fix] 요리 로딩바 오류 수정

---

Client/Code/CStageLoading.cpp
Client/Code/CUi_GameLoding.cpp

[Fix] 로딩창 수정 중

---

Client/Code/CStage.cpp
Engine/Code/CObjectPoolMgr.cpp
Engine/Header/CObjectPoolMgr.h
Reference/Header/CObjectPoolMgr.h

- 스테이지 종료시 ObjectPool에 L"Plate_" 키 값 벡터 지우는 함수 추가
- CStage에 GAME_END 될 때 해당 함수 호출

[Fix] : 스테이지 종료시 ObjectPool에 Plate에 벡터 클리어하게 수정
